export const CATEGORIES_INTERIOR_DOOR = 1;

export const CATEGORIES_FURNITURE_RYCHKI = 3;
export const CATEGORIES_FURNITURE_PETLY = 4;
export const CATEGORIES_FURNITURE_MEHANIZMY = 5;

export const CATEGORIES_MOULDING_DELEMENT = 6;
export const CATEGORIES_MOULDING_NELEMENT = 7;
export const CATEGORIES_MOULDING_CAPITALS = 8;
export const CATEGORIES_MOULDING_BOXES = 9;
